version: "3"

services:
  webapp: 
    build: .
    ports:
      - "8085:80"
    networks:
      - webnet
    environment:
      - PERSON=Covece
    container_name: webapp

  redis:
    image: redis
    ports: ["6379"]
    networks:
      - webnet
    volumes:
      - "redis-data:/data"
    container_name: redis

networks:
  webnet:

volumes:
  redis-data:

